### ISSUE TITLE
添加受管服务器时报错

### ISSUE THREAD

**Issue by smarty-kiki** [go-ireul/bastion#6]
<img width="497" alt="_25e5c514-1a9e-452f-a950-ee20785b761b" src="https://user-images.githubusercontent.com/1926941/30840969-b8b6099a-a2ac-11e7-9338-869364155434.png">

**Comment by yanke-guo** [comment]
数据库配置错误，修改了样板配置文件，增加了字符集的指定

b856ea17f97c191d32531f48bcf1c4a419ff27c1
